### PR TITLE
Problem Fix

### PR DESCRIPTION
**Pull request by hjung4**

### CODE REVIEW

**Comment by pi-plus-45x23** [comment]
What is it fixing? The current code ensures that the two numbers won't be relatively prime (yours doesn't guarantee that since it could still be the same prime...)

**Comment by hjung4** [comment]
Your code made it give any 2 numbers (even if they aren't prime).

**Comment by hjung4** [comment]
I played games on ftw-clone. They gave me numbers that are not prime. Other users have also noticed this.

**Comment by hjung4** [comment]
I've checked your code. Your code gives any two relatively prime numbers. For the Chicken McNugget Theorem to work, **the 2 numbers both need to be prime.**

**Comment by gamester543** [comment]
Tell me when you want me to merge. Also, can you first make it so it queries the array length dynamically, e.g. primes.length instead of writing "24".

**Comment by pi-plus-45x23** [comment]
hjung the numbers don't have to be prime, just relatively prime. https://artofproblemsolving.com/wiki/index.php?title=Chicken_McNugget_Theorem

**Pull request merged**
