### PR TITLE
better problems

### PR DESCRIPTION
**Pull request by hqptic45508**
better temporary problems instead of lame computational ones. I'll add more later.

### CODE REVIEW

**Comment by gamester543** [comment]
I think its better to have dynamically generated problems. Cycling through 15 problems will get boring fast.

**Comment by hqptic45508** [comment]
yeah i'm working on that right now. I might create some problem sets but I need help on generating random numbers and generating even numbers and generating relatively prime numbers. do you know how to do that

**Comment by gamester543** [comment]
Try using Math.random().

**Comment by hqptic45508** [comment]
is there a function like
randInt[1, 3, 5, 7, 9]
where it chooses one of those numbers?

**Comment by gamester543** [comment]
https://www.freecodecamp.org/challenges/generate-random-whole-numbers-with-javascript

**Pull request closed without merging**
